### ISSUE TITLE
Failed upgrading from 2.38.0 to 2.45.0

### ISSUE THREAD

**Issue by kalEl2001** [Kong/charts#1199]
When I tried to upgrade Kong from chart version 2.38.0 to 2.45.0 the ingress controller container always crashes. When I check the logs of the container, it shows that there is this error
```
E1218 02:10:31.569894       1 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
	goroutine 413 [running]:
	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x26f0068, 0x39fa480}, {0x2028900, 0x399b6e0})		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:107 +0xbc
	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x26f0068, 0x39fa480}, {0x2028900, 0x399b6e0}, {0x39fa480, 0x0, 0x100000000000000?})
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:82 +0x5e
	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:59 +0x108
	panic({0x2028900?, 0x399b6e0?})
		/usr/local/go/src/runtime/panic.go:785 +0x132
	github.com/kong/kubernetes-ingress-controller/v3/internal/controllers/configuration.(*KongUpstreamPolicyReconciler).getUpstreamPoliciesForIngressServices(0xc0000ee0e0, {0x26f02d0, 0xc000833090}, {0x271ba90?, 0xc000bc0420})
		/workspace/internal/controllers/configuration/kongupstreampolicy_controller.go:327 +0xb2
	sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc[...]).mapAndEnqueue(0x2717080?, {0x26f02d0, 0xc000833090?}, {0x27008e0?, 0xc00006ad40}, {0x271ba90, 0xc000bc0420?}, 0xc000853cd0?)
		/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/handler/enqueue_mapped.go:119 +0x67
	sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc[...]).Create(...)
		/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/handler/enqueue_mapped.go:84
	sigs.k8s.io/controller-runtime/pkg/internal/source.(*EventHandler[...]).OnAdd(0x40a280, {0x2361b60?, 0xc000bc0420})
		/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/source/event_handler.go:92 +0x255
	k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
		/home/runner/go/pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/controller.go:246
	k8s.io/client-go/tools/cache.(*processorListener).run.func1()
		/home/runner/go/pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/shared_informer.go:978 +0x139
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:226 +0x33
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000853f70, {0x26d1240, 0xc001b2a600}, 0x1, 0xc001b3e770)
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:227 +0xaf
	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c1af70, 0x3b9aca00, 0x0, 0x1, 0xc001b3e770)
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:204 +0x7f
	k8s.io/apimachinery/pkg/util/wait.Until(...)
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:161
	k8s.io/client-go/tools/cache.(*processorListener).run(0xc0009d81b0)
		/home/runner/go/pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/shared_informer.go:972 +0x5a
	k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/wait.go:72 +0x4c
	created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 352
		/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/wait.go:70 +0x73
 >
```
I use ArgoCD v2.12.3. Please also help fix the logging so that the whole stack trace is logged as one log (the app version running on chart version 2.38.0 logged the stack trace as one log for every line of the stack trace). Thank you 🙏

**Comment by pmalek** [comment]
Hey @kalEl2001 👋 

This has been fixed in https://github.com/Kong/kubernetes-ingress-controller/pull/6651 and will be released in 3.4 (which will happen any day now).

> Please also help fix the logging so that the whole stack trace is logged as one log (the app version running on chart version 2.38.0 logged the stack trace as one log for every line of the stack trace).

I'm not sure this is something that is something we easily control or have knowingly changed. 🤔 

For posterity: 2.38.0 used KIC 3.1 while 2.45 uses 3.3.

**Comment by kalEl2001** [comment]
Hi @pmalek , thank you for your response. 🙏 Looking forward for the update 😀

**Comment by pmalek** [comment]
3.4 is out and should be able to use it: https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v3.4.0

Let me know if that fixes your issue @kalEl2001.

**Comment by kalEl2001-cc** [comment]
I have updated the chart version back to 2.45.0 while overriding the ingress controller image tag value to 3.4 and I think it is working now. Thank you for your help @pmalek !

**Comment by kalEl2001** [comment]
I have updated the chart version back to 2.45.0 while overriding the ingress controller image tag value to 3.4 and I think it is working now. Thank you for your help @pmalek ! Closing this issue 🙏
