### ISSUE TITLE
New containers restarting during RollingUpdate

### ISSUE THREAD

**Issue by brennoo** [Kong/charts#526]
Hello,

We have a kong deployment with the following config:
```yaml
deployment:
  namespace: "kong-ingress-controller"

resources:
  limits:
    cpu: 500m
    memory: 512M
  requests:
    cpu: 500m
    memory: 512M

updateStrategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: "100%"
     maxUnavailable: "0%"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 30

image:
  repository: kong
  tag: "2.7"

env:
  prefix: /kong_prefix/
  database: "off"
  nginx_worker_processes: "2"
  plugins: "prometheus,jwt"


ingressController:
  enabled: true
  installCRDs: false
  ingressClass: kong-public

proxy:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:xxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "kong-proxy"
    external-dns.alpha.kubernetes.io/hostname: "ingress.example.com"


topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
```

and during the rolling update the new containers restarts 1-2 times before getting online, is that normal ? these are the logs:

```shell
$ kubectl -n kong-ingress-controller rollout restart deploy/public02-kong && kt public02-kong -n kong-ingress-controller
deployment.apps/public02-kong restarted
Will tail 18 logs...
public02-kong-66c9c956b4-7kzhc ingress-controller
public02-kong-66c9c956b4-7kzhc proxy
public02-kong-66c9c956b4-7kzhc clear-stale-pid
public02-kong-66c9c956b4-jmpsw ingress-controller
public02-kong-66c9c956b4-jmpsw proxy
public02-kong-66c9c956b4-jmpsw clear-stale-pid
public02-kong-66c9c956b4-w5t5k ingress-controller
public02-kong-66c9c956b4-w5t5k proxy
public02-kong-66c9c956b4-w5t5k clear-stale-pid
public02-kong-7864676dd6-djdwj ingress-controller
public02-kong-7864676dd6-djdwj proxy
public02-kong-7864676dd6-djdwj clear-stale-pid
public02-kong-7864676dd6-ldrsq ingress-controller
public02-kong-7864676dd6-ldrsq proxy
public02-kong-7864676dd6-ldrsq clear-stale-pid
public02-kong-7864676dd6-zxln6 ingress-controller
public02-kong-7864676dd6-zxln6 proxy
public02-kong-7864676dd6-zxln6 clear-stale-pid
Error from server (BadRequest): container "ingress-controller" in pod "public02-kong-7864676dd6-djdwj" is waiting to start: PodInitializing
Error from server (BadRequest): container "proxy" in pod "public02-kong-7864676dd6-djdwj" is waiting to start: PodInitializing
Error from server (BadRequest): container "ingress-controller" in pod "public02-kong-7864676dd6-zxln6" is waiting to start: PodInitializing
Error from server (BadRequest): container "proxy" in pod "public02-kong-7864676dd6-ldrsq" is waiting to start: PodInitializing
Error from server (BadRequest): container "proxy" in pod "public02-kong-7864676dd6-zxln6" is waiting to start: PodInitializing
Error from server (BadRequest): container "ingress-controller" in pod "public02-kong-7864676dd6-ldrsq" is waiting to start: PodInitializing
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.service reconciler group= reconciler kind=Service
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.service reconciler group= reconciler kind=Service
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="stop status update channel."
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.secret reconciler group= reconciler kind=Secret
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.secret reconciler group= reconciler kind=Secret
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="All workers finished" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
[public02-kong-66c9c956b4-w5t5k ingress-controller] time="2022-01-12T11:58:19Z" level=info msg="context done: shutting down the proxy update server" subsystem=proxy-cache-resolver
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.secret reconciler group= reconciler kind=Secret
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="stop status update channel."
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.service reconciler group= reconciler kind=Service
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.secret reconciler group= reconciler kind=Secret
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="context done: shutting down the proxy update server" subsystem=proxy-cache-resolver
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=error msg="context completed with error" error="context canceled" subsystem=proxy-cache-resolver
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=info msg="All workers finished" logger=controller.service reconciler group= reconciler kind=Service
[public02-kong-66c9c956b4-jmpsw ingress-controller] time="2022-01-12T11:58:20Z" level=error msg="error received after stop sequence was engaged" error="context canceled"
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.tcpingress reconciler group=configuration.konghq.com reconciler kind=TCPIngress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.udpingress reconciler group=configuration.konghq.com reconciler kind=UDPIngress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.kongingress reconciler group=configuration.konghq.com reconciler kind=KongIngress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="context done: shutting down the proxy update server" subsystem=proxy-cache-resolver
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.endpoints reconciler group= reconciler kind=Endpoints
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.secret reconciler group= reconciler kind=Secret
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=error msg="context completed with error" error="context canceled" subsystem=proxy-cache-resolver
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.kongplugin reconciler group=configuration.konghq.com reconciler kind=KongPlugin
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.service reconciler group= reconciler kind=Service
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.service reconciler group= reconciler kind=Service
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.secret reconciler group= reconciler kind=Secret
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.kongclusterplugin reconciler group=configuration.konghq.com reconciler kind=KongClusterPlugin
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.ingress reconciler group=networking.k8s.io reconciler kind=Ingress
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="stop status update channel."
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
[public02-kong-66c9c956b4-7kzhc ingress-controller] time="2022-01-12T11:58:26Z" level=info msg="All workers finished" logger=controller.kongconsumer reconciler group=configuration.konghq.com reconciler kind=KongConsumer
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: signal 3 (SIGQUIT) received from 1110, shutting down
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1096#0: gracefully shutting down
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1097#0: gracefully shutting down
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1096#0: exiting
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1097#0: exiting
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1097#0: exit
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: signal 17 (SIGCHLD) received from 1097
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: worker process 1097 exited with code 0
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: signal 29 (SIGIO) received
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1096#0: exit
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: signal 17 (SIGCHLD) received from 1096
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: worker process 1096 exited with code 0
[public02-kong-66c9c956b4-w5t5k proxy] 2022/01/12 11:58:34 [notice] 1#0: exit
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: signal 3 (SIGQUIT) received from 1110, shutting down
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1096#0: gracefully shutting down
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1097#0: gracefully shutting down
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1096#0: exiting
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1097#0: exiting
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1097#0: exit
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: signal 17 (SIGCHLD) received from 1097
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: worker process 1097 exited with code 0
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: signal 29 (SIGIO) received
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1096#0: exit
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: signal 17 (SIGCHLD) received from 1096
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: worker process 1096 exited with code 0
[public02-kong-66c9c956b4-jmpsw proxy] 2022/01/12 11:58:35 [notice] 1#0: exit
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: signal 3 (SIGQUIT) received from 1111, shutting down
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1097#0: gracefully shutting down
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1098#0: gracefully shutting down
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1098#0: exiting
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1097#0: exiting
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1098#0: exit
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: signal 17 (SIGCHLD) received from 1098
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: worker process 1098 exited with code 0
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: signal 29 (SIGIO) received
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1097#0: exit
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: signal 17 (SIGCHLD) received from 1097
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: worker process 1097 exited with code 0
[public02-kong-66c9c956b4-7kzhc proxy] 2022/01/12 11:58:41 [notice] 1#0: exit
```

new pods:

```shell
$ kgp -n kong-ingress-controller
NAME                             READY   STATUS    RESTARTS   AGE
public02-kong-7864676dd6-djdwj   2/2     Running   2          3m5s
public02-kong-7864676dd6-ldrsq   2/2     Running   2          3m5s
public02-kong-7864676dd6-zxln6   2/2     Running   2          3m5s
```

**Comment by brennoo** [comment]
I guess it might be related with admin api no being ready yet ? these logs are from ingress-controller pod:
```shell
time="2022-01-12T14:36:25Z" level=info msg="diagnostics server disabled"
time="2022-01-12T14:36:25Z" level=info msg="starting controller manager" commit=119dca97739dafee5f0539b96774144754328e8d logger=setup release=2.1.1 repo="https://github.com/Kong/kubernetes-ingress-controller.git"
time="2022-01-12T14:36:25Z" level=info msg="getting enabled options and features" logger=setup
time="2022-01-12T14:36:25Z" level=info msg="getting the kubernetes client configuration" logger=setup
W0112 14:36:25.417638       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-12T14:36:25Z" level=info msg="getting the kong admin api client configuration" logger=setup
time="2022-01-12T14:36:25Z" level=error msg="tag filtering disabled because Kong Admin API does not support tags" error="making HTTP request: Get \"https://localhost:8444/tags\": dial tcp 127.0.0.1:8444: connect: connection refused" logger=setup
Error: could not retrieve Kong admin root: making HTTP request: Get "https://localhost:8444/": dial tcp 127.0.0.1:8444: connect: connection refused
Error: could not retrieve Kong admin root: making HTTP request: Get "https://localhost:8444/": dial tcp 127.0.0.1:8444: connect: connection refused
```

**Comment by rainest** [comment]
The controller restarting a few times is normal, since it comes up faster than Kong and may reach its timeout waiting for the admin API to become ready.

Kong generally should not restart. You'll likely want to increase the RAM allocation to at least 1G: it looks like it's not coming online fast enough for Kubernetes to consider it live and forces it to restart, which usually indicates that it's under-provisioned.

**Comment by prousso** [comment]
I reproduce with significant resource on RAM and CPU and pods restart very often :/ 

PS: I don't have any trouble with KIC <2.0

**Comment by seany89** [comment]
@brennoo What version of the chart are you experiencing this on?

I see it on version `2.7.0` which can be up to 5 restarts on a pod sometimes, we run as a daemonSet.

**Comment by seany89** [comment]
Getting this on chart version `2.12.0` running as a daemon set.
Error `could not retrieve Kong admin root` one pod has an issue starting rest are fine.

**Comment by rainest** [comment]
The chart version, broadly, shouldn't affect this--really only the behavior of the Kong image should. Technically the controller could also fail to start, but it usually only fails to start because it was unable to connect to Kong at startup (that's what causes the `could not retrieve Kong admin root` message indicates).

You could try creating a container with additional NGINX-level debug logs by checking out the build tools repo, changing https://github.com/Kong/kong-build-tools/blob/98d007c773bf646847aa091d103a4a9cb5bf55f5/openresty-build-tools/kong-ngx-build#L22 to `DEBUG=1` and running:

```
make package-kong
KONG_TEST_CONTAINER_NAME=myuser/kong:3.0.0-debug make build-test-container
```

(from https://github.com/Kong/kong-build-tools#building-a-kong-package and https://github.com/Kong/kong-build-tools#building-a-kong-docker-image).

In testing I've occasionally seen where Kong fails to ever call `bind()` for its various listens, but that wasn't on a release build, isn't something I could replicate reliably, and isn't obviously explained (the only thing our code controls for those binds is configuration generation--the actual code that handles the bind call is all NGINX).

**Comment by brennoo** [comment]
hey all,

The issue was fixed here: https://github.com/Kong/kubernetes-ingress-controller/issues/2274

Then we have set the following values in our chart to fix the reboots:

```yaml
env:
  admin_listen: "127.0.0.1:8444 ssl"

ingressController:
 image:
    tag: "2.4"
  env:
    kong_admin_init_retries: 5
    kong_admin_init_retry_delay: "20s"
```

**Comment by NICK-DUAN** [comment]
Maybe I figured out why this problem occurs.

My old charts version is `1.7.0`, And I want to upgrade to `2.30.0`, then I diff two deployment, I found `2.30.0` has `securityContext` like this:

```yaml
securityContext:
  capabilities:
    drop:
      - ALL
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
```

Then I delete this, container `proxy` start running, but container `ingress-controller` got another problem, always restart, and print log like this:
```bash
time="2024-01-29T09:58:38Z" level=info msg="Starting workers" logger=controllers.Dynamic/KnativeV1Alpha1/Ingress worker count=1
time="2024-01-29T09:58:38Z" level=info msg="Starting workers" logger=controllers.KongClusterPlugin worker count=1
time="2024-01-29T09:58:45Z" level=info msg="successfully synced configuration to Kong" update_strategy=InMemory url="https://localhost:8444"
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 140 [running]:
	>  runtime/debug.Stack()
	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Error(0xc0000c3740, {0x2194ec0, 0xc001cd7760}, {0x1ed57a4, 0x21}, {0x0, 0x0, 0x0})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/deleg.go:139 +0x5d
	>  github.com/go-logr/logr.Logger.Error({{0x21b5f28?, 0xc0000c3740?}, 0x0?}, {0x2194ec0, 0xc001cd7760}, {0x1ed57a4, 0x21}, {0x0, 0x0, 0x0})
	>  	/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299 +0xda
	>  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1({0x21b2590?, 0xc000868a00?})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:68 +0x1a9
	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2(0xc0012b2e00?, {0x21b2590?, 0xc000868a00?})
	>  	/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/loop.go:73 +0x52
	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext({0x21b2590, 0xc000868a00}, {0x21a8ef0?, 0xc000856960}, 0x1, 0x0, 0x0?)
	>  	/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/loop.go:74 +0x233
	>  k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel({0x21b2590, 0xc000868a00}, 0x0?, 0x0?, 0x0?)
	>  	/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/poll.go:33 +0x56
	>  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1()
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:56 +0xee
	>  created by sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start in goroutine 147
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:48 +0x1d8
```
by the way, cluster is `TKE`(`Tencent Kubernetes Engine`)

**Comment by NICK-DUAN** [comment]
new `custom-values.yaml`
```yaml
proxy:
  type: ClusterIP
env:
  admin_listen: "127.0.0.1:8444 ssl"
ingressController:
  env:
    kong_admin_init_retries: 5
    kong_admin_init_retry_delay: "20s"
  ingressClass: "testkong"
admin:
  enabled: true
  tls:
    enabled: true
  type: ClusterIP
containerSecurityContext: {}
replicaCount: 1
manager:
  enabled: false
portal:
  enabled: false
portalapi:
  enabled: false
cluster:
  enabled: false
clustertelemetry:
  enabled: false
```
